# Generated by Django 4.0.6 on 2022-07-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorPatientApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
    ]
