# Generated by Django 4.0.6 on 2022-07-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorPatientApp', '0006_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_you_want',
            field=models.DateField(),
        ),
    ]
