# Generated by Django 4.0.6 on 2022-07-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorPatientApp', '0007_alter_appointment_date_you_want'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.CharField(default='', max_length=550),
        ),
    ]
