# Generated by Django 4.0.6 on 2022-07-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorPatientApp', '0008_appointment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
