# Generated by Django 4.0.6 on 2022-07-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorPatientApp', '0009_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=-1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
