# Generated by Django 4.0.6 on 2022-07-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorPatientApp', '0011_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images/noimage.jpg', null=True, upload_to='images/'),
        ),
    ]
