# Generated by Django 4.0.6 on 2022-07-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorPatientApp', '0012_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_you_want',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='templates/images/noimage.jpg', null=True, upload_to='images/'),
        ),
    ]
