# Generated by Django 4.0.6 on 2022-07-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorPatientApp', '0013_alter_appointment_date_you_want_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_you_want',
            field=models.DateField(),
        ),
    ]
